### ISSUE TITLE
Library doesn't work (2 critical bugs)

### ISSUE THREAD

**Issue by ftdot** [ftdot/ezlog#4]
## Critical bug 1

Library crashed after using any handler through `ezlog.LogLevel` class:

```py
Traceback (most recent call last):
  File "...\bot.py", line 5, in <module>
    from app import bot, logger, database, translator
  File "...\app.py", line 34, in <module>
    stdh        = ezlog.StdoutHandler(log_level=ezlog.LogLevel.DEBUG)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "...\handlers.py", line 113, in __init__
    super().__init__(sys.stdout, **kwargs)
  File "...\handlers.py", line 35, in __init__
    self.log_level   = log_level if isinstance(log_level, LogLevel) else {v: k for k, v in level_names.items()}[log_level.upper()]
                                                                                                                ^^^^^^^^^^^^^^^
AttributeError: 'int' object has no attribute 'upper'
```

Code:

```py
stdh        = ezlog.StdoutHandler(log_level=ezlog.LogLevel.DEBUG) #! log_level=ezlog.LogLevel.DEBUG
foh         = ezlog.FileHandler(f'logs/bot-{ezlog.Logger("temp").format_time(datetime.now()).translate(FORBIDDEN_CHARS)}.log',
                                log_level='debug')
main_group  = ezlog.LoggerGroup('Bot', handlers=[stdh, foh])
logger      = ezlog.Logger('Main', group=main_group)
```

## Critical bug 2

By using string as log level library is work. But, not successful. Logging doesn't work, any log level, message, format variables.

Code:

```py
stdh        = ezlog.StdoutHandler(log_level='debug')
foh         = ezlog.FileHandler(f'logs/bot-{ezlog.Logger("temp").format_time(datetime.now()).translate(FORBIDDEN_CHARS)}.log',
                                log_level='debug')
main_group  = ezlog.LoggerGroup('Bot', handlers=[stdh, foh])
logger      = ezlog.Logger('Main', group=main_group)

# logging test
logger.debug('test')
logger.exception('test')
logger.info('test')
logger.warning('test')
logger.error('test')
logger.critical('test')
```

No one log in the file, no one log in the console.

**Comment by ftdot** [comment]
Fixed in `v1.0.1`
